import type { Metadata } from "next";
import localFont from "next/font/local";
import { Rubik } from 'next/font/google';
import "./globals.css";
import { NavigationBar } from "@/components/navbar/navigation-menu";
import { Toaster } from "@/components/ui/toaster";
import { ClerkProvider } from '@clerk/nextjs'
import Providers from "@/providers";
import Header from "@/components/Header";
import { ThemeProvider } from "@/components/theme-provider";


const rubik = Rubik({ subsets: ['latin'] });

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${rubik.className} text-primary light:bg-primary-light dark:bg-primary-dark dark:text-white min-h-screen antialiased`}
        >
        <Providers>
          <div className="bg-mobile-pattern md:bg-tablet-pattern lg:bg-desktop-pattern dark:bg-mobile-pattern-dark dark:md:bg-tablet-pattern-dark dark:lg:bg-desktop-pattern-dark bg-no-repeat min-h-screen">
          <NavigationBar/>
            {children}
            <Toaster/>
          </div>
        </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
